### ISSUE TITLE
Conflict between NewRelic Agent and Guardsquare plugin

### ISSUE THREAD

**Issue by fillipeoliveira-hotmart** [newrelic/newrelic-android-agent#560]
## Description

There is a build classpath dependency conflict between the **New Relic Android Agent Gradle Plugin** (v7.7.6) and the **Guardsquare Gradle Plugin** when both are declared together in the root `build.gradle.kts` file.

When the New Relic plugin is applied, executing any Guardsquare Gradle task (such as `./gradlew guardsquareDownloadCli`) fails with a `NoSuchMethodError` / `Unable to find method` exception.

## Steps to Reproduce

A sample app with the error can be found on: https://github.com/fillipeoliveira-hotmart/dexguard-newrelic-sample

1. Add both, newrelic and guardsquare plugin on `build.gradle.kts` `plugins` block.
2. run `./gradlew guardsquareDownloadCli` gradle command

## Expected Behavior

The Gradle build should complete successfully without any classpath collision or NoSuchMethodError. The New Relic Gradle plugin should not force or downgrade commons-io (or other shared utility libraries) on the root buildscript classpath in a way that breaks other applied plugins.

## Relevant Logs / Console output

```
Unable to find method ''java.nio.file.attribute.FileTime org.apache.commons.io.file.attribute.FileTimes.fromUnixTime(long)''
'java.nio.file.attribute.FileTime org.apache.commons.io.file.attribute.FileTimes.fromUnixTime(long)'
```

## Your Environment

• New Relic Android Agent Gradle Plugin Version: 7.7.6
• Guardsquare Gradle Plugin Version: +
• Gradle Version: 9.4.1
• Android Gradle Plugin (AGP) Version: 9.2.1
• Kotlin Version: 2.2.10
• Operating System: macOS

**Comment by Newrelic-Boomi** [comment]
https://new-relic.atlassian.net/browse/NR-577053

**Comment by ndesai-newrelic** [comment]
Thanks for the detailed report and the reproducer repo — that made the root cause straightforward to confirm.

## Root cause

The agent's Gradle plugin was bundling `commons-io` into the plugin jar **without relocating it**, pinned to an older version (2.12.0). When the plugin is applied alongside the Guardsquare/DexGuard plugin, both land on the shared root buildscript classloader. That classloader resolves `org.apache.commons.io.file.attribute.FileTimes` to our bundled 2.12.0 copy, which does **not** contain `fromUnixTime(long)` — that method was added in commons-io **2.16.0**. Guardsquare calls it, the older class wins on the classpath, and you get the `NoSuchMethodError`.

## Fix

We now relocate the bundled `commons-io` into the `com.newrelic.*` namespace so it no longer leaks onto the shared buildscript classpath and can't collide with the version other plugins need.

A snapshot build with the fix is available as **`7.7.8-SNAPSHOT`**. Could you verify it against your reproducer?

> Note: your project uses the Kotlin DSL (`build.gradle.kts`). The snippets below are in Groovy — adapt the `maven { }` blocks accordingly, e.g. `maven { url = uri("https://central.sonatype.com/repository/maven-snapshots/") }`.

### 1. `settings.gradle`

```groovy
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Snapshot repository
        maven {
            name = 'Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'
        }
    }
}
```

### 2. Project-level `build.gradle`

```groovy
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            name = "Central Portal Snapshots"
            url = "https://central.sonatype.com/repository/maven-snapshots/"
        }
    }
    dependencies {
        classpath "com.newrelic.agent.android:agent-gradle-plugin:7.7.8-SNAPSHOT"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            name = "Central Portal Snapshots"
            url = "https://central.sonatype.com/repository/maven-snapshots/"
        }
    }
}
```

### 3. App-level `build.gradle`

```groovy
dependencies {
    implementation 'com.newrelic.agent.android:android-agent:7.7.8-SNAPSHOT'
}
```

Then re-run `./gradlew guardsquareDownloadCli` and let us know whether the conflict is resolved. Thanks for your patience!

**Comment by fillipeoliveira-hotmart** [comment]
Hello,

I do tests and this snapshot versions solve the problem

<img width="365" height="31" alt="Image" src="https://github.com/user-attachments/assets/02239175-7347-46fb-8cc9-cd898a6b655d" />

Thx for the help, and let me know when this version will be release!
